# Generated by Django 5.1.15 on 2026-04-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0061_task_project_file_upload_idx_async"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="review_comment",
            field=models.TextField(
                blank=True,
                help_text="Comment from reviewer, especially rejection reasons",
                null=True,
                verbose_name="review comment",
            ),
        ),
    ]
