# Generated by Django 5.1.15 on 2026-04-09 11:58

from django.db import migrations


def add_uncompleted_filter_to_defaults(apps, schema_editor):
    """Add 'completed_at is empty' filter to each project's Default view."""
    View = apps.get_model('data_manager', 'View')
    FilterGroup = apps.get_model('data_manager', 'FilterGroup')
    Filter = apps.get_model('data_manager', 'Filter')

    for view in View.objects.all():
        title = (view.data or {}).get('title', '')
        if title != 'Default':
            continue

        fg = view.filter_group
        if not fg:
            fg = FilterGroup.objects.create(conjunction='and')
            view.filter_group = fg
            view.save()

        # Skip if filter already exists
        if fg.filters.filter(column='filter:tasks:completed_at', operator='empty').exists():
            continue

        f = Filter.objects.create(
            column='filter:tasks:completed_at',
            type='Datetime',
            operator='empty',
            value='yes',
        )
        fg.filters.add(f)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("data_manager", "0018_remove_allow_skip"),
    ]

    operations = [
        migrations.RunPython(add_uncompleted_filter_to_defaults, noop),
    ]
