# Generated by Django 5.1.15 on 2026-04-08 13:46

from django.db import migrations


def backfill_project_members(apps, schema_editor):
    """Create ProjectMember records for users who have annotations in each project."""
    Annotation = apps.get_model('tasks', 'Annotation')
    ProjectMember = apps.get_model('projects', 'ProjectMember')

    # Get distinct (user, project) pairs from annotations
    pairs = (
        Annotation.objects.filter(completed_by__isnull=False)
        .values_list('completed_by_id', 'project_id')
        .distinct()
    )

    created = 0
    for user_id, project_id in pairs:
        _, was_created = ProjectMember.objects.get_or_create(
            user_id=user_id,
            project_id=project_id,
            defaults={'enabled': True},
        )
        if was_created:
            created += 1


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_project_annotator_evaluation_enabled"),
    ]

    operations = [
        migrations.RunPython(backfill_project_members, noop),
    ]
