# Generated by Django 5.1.15 on 2026-04-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_custom_hotkeys"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user has been approved by an administrator to access the platform.",
                verbose_name="approved",
            ),
        ),
    ]
