# Generated by Django 5.1.15 on 2026-04-08 13:40

from django.db import migrations, models


def approve_existing_staff(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(
        models.Q(is_staff=True) | models.Q(is_superuser=True)
    ).update(is_approved=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_is_approved"),
    ]

    operations = [
        migrations.RunPython(approve_existing_staff, noop),
    ]
